intel_root='/opt/intel/'

env = Environment(CPPPATH= ['include', 'src',
                        # intel_root + 'athena/utils/include',
                        intel_root + 'jarvis/include',
                        intel_root + 'jarvis/util',],
                        CXXFLAGS="-std=c++11 -O3")

source_files = ['src/TCIAMemSqlGen.cc',
                'src/memsqlgen.cc',
                ]

env.Program('tcia_memsql_gen', source_files,
            LIBS = ['jarvis', 'jarvis-util', 'jsoncpp'],
            LIBPATH = ['/usr/lib/x86_64-linux-gnu/',
                        intel_root + 'jarvis/lib/',
                        # intel_root + 'athena/utils/',
                       ]
            )

